### PR TITLE
Feature/mergetoprod

### PR DESCRIPTION
**Pull request by iamandycohen**

### CODE REVIEW

**Comment by sc-dawidrutkowski** [comment]
@matkovskyi @StanislavStativa Please review.

**Review by StanislavStativa — APPROVED** [review]

**Review by matkovskyi — APPROVED** [review]

**Comment by sc-dawidrutkowski** [comment]
@iamandycohen I think we also need to include this PR: https://github.com/sitecorelabs/xmcloud-foundation-head-staging/pull/23#pullrequestreview-1282965404 which has been merged to the staging repo a few seconds ago.

**Review by ambrauer — CHANGES_REQUESTED** [review]
The bulk of these changes are coming from the JSS canary version which is being used on staging and but can't go to prod...

**Comment by sc-dawidrutkowski** [comment]
@ambrauer Which means that we won't be able to use FEaaS Component on prod?

**Comment by ambrauer** [comment]
@sc-dawidrutkowski Right, but that's not ready until end of the month as I understand it (we can clarify at our FEaaS sync meeting).

**Pull request closed without merging**
