### PR TITLE
I observed that lot of developers are falling in an error where their…

### PR DESCRIPTION
**Pull request by daivagna**
… computer gets restarted and iis is started again and the upscript which was working just fails after retsart of the computer, so i think there is no harm in brining in iis reset in up script so it first stops it and then proceeeds

### CODE REVIEW

**Comment by Elyseum** [comment]
iisreset requires admin rights to run (at least on my environment) and up.ps1 is intended to run without admin rights, so this might not work on all setups.

**Comment by daivagna** [comment]
you have to open powershell in admin mode to run up script, right? otherwise it might have some rights level issues @Elyseum ? not sure if it runs without that too

**Comment by Elyseum** [comment]
The readme only mentions admin for Init.ps1 (https://github.com/sitecorelabs/xmcloud-foundation-head/blob/main/README.md). It's needed to modify your hosts file.
I run the Up.ps1 script with regular access rights (e.g. from the integrated console in my vscode).

**Comment by daivagna** [comment]
Ok, not sure what is the other way around, but when you restart your computer and same up script fails until you find out IIS is running, **It make sense what you are saying about running script in ADMIN mode is not needed** but with iisreset.exe /stop  it will require, just like init script which is adding a host file, **is it a right reason to say, you need to open up script also in ADMIN mode? being the main script**, it will save lot of time of troubleshooting, if it's from security purpose we are not allowing then its a different story

But do let me know else i will cancel the PR, but i have seen lot of developers are struggling to find why UP script which was working just does not work until they find out that it was restarted and IIS again started

**Comment by Elyseum** [comment]
For the record, I'm not an admin / sitecore employee. So it's not up to me to accept / refuse PRs.

I just wanted to give my opinion on this because the issue you're addressing is worth the effort: it's correct that it can be very confusing / time wasting to have your start up fail because of IIS running.

**Comment by daivagna** [comment]
Appreciate your inputs, So what should be the next steps?

**Pull request closed without merging**
